# Generated by Django 4.2 on 2024-01-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('age', models.PositiveIntegerField(default=25)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=50, null=True)),
                ('image', models.ImageField(default='default_human.jpg', upload_to='uploads/images/')),
                ('address', models.TextField(max_length=255)),
            ],
        ),
    ]
