# Generated by Django 4.2 on 2024-01-29 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Human',
            new_name='Employee',
        ),
    ]
